apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: portworx-io-priority-high
provisioner: kubernetes.io/portworx-volume
parameters:
  priority_io: high
  repl: "1"
  snap_interval: "70"
reclaimPolicy: Delete
volumeBindingMode: Immediate
